
export type Language = 'vi' | 'en' | 'th' | 'vi-en';

export const translations = {
  vi: {
    title: "AI Tư Vấn",
    subtitle: "Phân Tích Nhanh",
    version: "v2.0 PRO",
    location: "Duy Tân Bình Dương • Trí Tuệ Kỹ Thuật",
    darkMode: "Chế độ Tối",
    lightMode: "Chế độ Sáng",
    optimizeCycle: "Tối ưu Chu kỳ",
    optimizeCycleDesc: "Phân tích 11 hạng mục chuyên sâu.",
    captureParams: "Chụp ảnh thông số",
    captureParamsDesc: "AI trích xuất dữ liệu từ ảnh màn hình máy.",
    aiExpert: "Chuyên gia AI",
    aiExpertDesc: "Hỗ trợ giải pháp kỹ thuật Duy Tân 24/7.",
    processing: "AI Đang Xử Lý...",
    ready: "Phân Tích Sẵn Sàng",
    newSession: "Phiên Mới",
    optimizationReport: "Phân Tích Nhanh",
    aiAssistant: "Trợ Lý Kỹ Thuật AI",
    thinking: "AI đang suy nghĩ...",
    chatPlaceholder: "Hỏi về làm nguội, nguyên liệu...",
    footer: "© 2024 AI Tối Ưu Hóa Ép Phun v2.0 - Kỹ Thuật Duy Tân Bình Dương",
    error: "Đã có lỗi xảy ra khi phân tích dữ liệu. Vui lòng kiểm tra lại kết nối hoặc AI.",
    noResponse: "Không có phản hồi từ AI.",
    connectionError: "Lỗi kết nối.",
    expertReplyError: "Xin lỗi, tôi không thể trả lời.",
    langVi: "Tiếng Việt",
    langEn: "English",
    langTh: "ไทย",
    langViEn: "Việt - Anh",
    inputParams: "Thông Số Đầu Vào",
    excelLabel: "Dòng Dữ Liệu Excel/CSV (Tab hoặc Phẩy)",
    excelPlaceholder: "Thứ tự cột: Thương hiệu, Model, Lực kẹp, Sản phẩm, Trọng lượng, Số lòng khuôn, Tổng chu kỳ, Bơm keo, Giữ áp, Làm mát, Nạp nhựa, Đóng khuôn, Mở khuôn, Lừa, Nhiệt nhựa, Nhiệt khuôn, Áp phun, Tốc độ phun, Tốc độ đóng, Tốc độ mở, Tốc độ lừa, Tốc độ nạp, Áp lưng, Vòng quay, Đệm keo, Lực kẹp thực, Tỷ lệ lỗi, Ghi chú",
    screenshotLabel: "Chụp Ảnh Màn Hình Máy",
    uploadPhoto: "Tải Ảnh Màn Hình",
    takePhoto: "Chụp ảnh trực tiếp",
    fromGallery: "Chọn từ thư viện",
    techNotes: "Ghi Chú Kỹ Thuật",
    techNotesPlaceholder: "vd: Tập trung giảm thời gian làm mát từ 15s xuống 10s, kiểm tra nhiệt độ khuôn...",
    analyzeBtn: "PHÂN TÍCH NHANH",
    resetBtn: "Đặt Lại",
    alertInput: "Vui lòng dán dữ liệu hoặc tải lên hình ảnh thông số.",
    chartCurrent: "Hiện tại",
    chartOptimized: "Tối ưu",
    chartCycleTime: "Tổng chu kỳ",
    chartCooling: "Làm mát",
    chartInjection: "Phun nhựa",
    chartHolding: "Giữ áp",
    chartCharging: "Nạp nhựa",
    chartMoldClose: "Đóng khuôn",
    chartMoldOpen: "Mở khuôn",
    chartEjection: "Lừa/Đẩy",
    chartOthers: "Khác",
    instCloseSpeed: "Đóng kềm {name}: Tăng tốc độ từ {orig}% lên {curr}%",
    instClosePos: "Đóng kềm {name}: Chỉnh vị trí từ {orig}mm thành {curr}mm",
    instOpenSpeed: "Mở kềm {name}: Tăng tốc độ từ {orig}% lên {curr}%",
    instOpenPos: "Mở kềm {name}: Chỉnh vị trí từ {orig}mm thành {curr}mm",
    instInjSpeed: "Bơm keo {name}: Chỉnh tốc độ từ {orig}% thành {curr}%",
    instInjPos: "Bơm keo {name}: Chỉnh vị trí từ {orig}mm thành {curr}mm",
    instHoldPress: "Giữ áp {name}: Chỉnh áp lực từ {orig} bar thành {curr} bar",
    instHoldTime: "Giữ áp {name}: Chỉnh thời gian từ {orig}s thành {curr}s",
    instChargeSpeed: "Nạp nhựa {name}: Chỉnh tốc độ từ {orig}% thành {curr}%",
    instChargePos: "Nạp nhựa {name}: Chỉnh vị trí từ {orig}mm thành {curr}mm",
    instCooling: "Thời gian Làm mát: Giảm từ {orig}s xuống {curr}s",
    simTitle: "Phân Tích Nhanh",
    moldName: "Tên khuôn",
    simDesc: "Đối chiếu thông số chuẩn và đề xuất điều chỉnh từ AI",
    simCurrent: "Chu kỳ hiện tại",
    simSimulated: "Chu kỳ mô phỏng",
    tableStandard: "Bảng 1: Thông Số Chuẩn (Hiện Tại)",
    tableProposed: "Bảng 2: AI Đề Xuất & Mô Phỏng",
    stage: "GIAI ĐOẠN",
    speed: "Tốc độ (%)",
    position: "Vị trí (mm)",
    pressure: "Áp lực (bar)",
    time: "Thời gian (s)",
    moldClose: "ĐÓNG KỀM (F3)",
    moldOpen: "MỞ KỀM",
    injection: "BƠM KEO",
    holding: "GIỮ ÁP",
    charging: "NẠP NHỰA",
    cooling: "LÀM MÁT",
    coolStdTime: "Thời gian làm mát chuẩn",
    coolAdjTime: "Điều chỉnh thời gian làm mát",
    ejection: "LỪA (EJECTION)",
    adjustment: "ĐIỀU CHỈNH",
    expected: "Dự kiến",
    standard: "Chuẩn",
    confirmed: "ĐÃ XÁC NHẬN ĐIỀU CHỈNH",
    confirmBtn: "XÁC NHẬN & XUẤT HƯỚNG DẪN",
    instTitle: "HƯỚNG DẪN ĐIỀU CHỈNH CHI TIẾT",
    instSubtitle: "Thực hiện chính xác các bước sau trên màn hình máy ép",
    printBtn: "In Hướng Dẫn",
    chartBrandTitle: "Chu Kỳ Trung Bình Theo Thương Hiệu (s)",
    chartCompositionTitle: "Cấu Thành Chu Kỳ",
    chartTitle: "BIỂU ĐỒ SO SÁNH CHU KỲ (GIÂY)",
    diffChart: "Biểu Đồ Chênh Lệch Chi Tiết",
    tableDetail: "Bảng So Sánh Chi Tiết Chu Kỳ",
    item: "Hạng mục",
    saving: "Tiết kiệm",
    coreIn: "Trung tử vào",
    coreOut: "Trung tử ra",
    robot: "Tổng SP (Robot)",
    waitRobot: "Chờ robot",
    adminDashboard: "Bảng Điều Khiển Admin",
    usageHistory: "Lịch sử sử dụng",
    totalAnalyses: "Tổng số lượt phân tích",
    activeUsers: "Số user đã sử dụng",
    todayAnalyses: "Số lượt hôm nay",
    weekAnalyses: "Số lượt tuần này",
    errorAnalyses: "Số record lỗi",
    topDepartment: "Bộ phận sử dụng nhiều nhất",
    historyTime: "Thời gian",
    user: "Người dùng",
    email: "Email",
    department: "Bộ phận",
    language: "Ngôn ngữ",
    status: "Trạng thái",
    currentCycle: "Chu kỳ hiện tại",
    targetCycle: "Chu kỳ mục tiêu",
    estimatedReduction: "Mức giảm ước tính",
    viewDetail: "Xem chi tiết",
    filterByDate: "Lọc theo ngày",
    filterByUser: "Lọc theo user",
    filterByDept: "Lọc theo bộ phận",
    filterByStatus: "Lọc theo trạng thái",
    filterByLang: "Lọc theo ngôn ngữ",
    searchPlaceholder: "Tìm kiếm theo email hoặc tên...",
    exportExcel: "Xuất Excel",
    exportCsv: "Xuất CSV",
    printReport: "In báo cáo",
    deleteRecord: "Xóa record",
    confirmDelete: "Bạn có chắc chắn muốn xóa record này?",
    analysisDetail: "Chi tiết phân tích",
    inputData: "Dữ liệu đầu vào",
    aiRecommendations: "Đề xuất AI",
    processingTime: "Thời gian xử lý",
    loginWithGoogle: "Đăng nhập với Google",
    logout: "Đăng xuất",
    notAuthorized: "Bạn không có quyền truy cập trang này.",
    backToApp: "Quay lại ứng dụng",
    statsByDay: "Số lượt sử dụng theo ngày",
    topUsers: "Top user sử dụng nhiều nhất",
    topDepts: "Top bộ phận sử dụng nhiều nhất",
    statusRatio: "Tỷ lệ trạng thái",
    avgReduction: "Trung bình mức giảm chu kỳ",
    all: "Tất cả",
    completed: "Hoàn thành",
    errorStatus: "Lỗi",
    processingStatus: "Đang xử lý",
    actions: "Thao tác",
    noRecords: "Không tìm thấy dữ liệu",
    usersList: "Danh sách người dùng",
    viewHistory: "Xem lịch sử",
    lastActive: "Hoạt động cuối",
    totalAnalysesUser: "Tổng số lượt",
    role: "Vai trò",
    recordsTab: "Bản ghi",
    usersTab: "Người dùng",
    confirmSaveTitle: "Kết quả phân tích",
    confirmSaveContent: "Bạn có muốn kết quả phân tích tư vấn nhanh?",
    confirmOk: "Xác nhận OK",
    cancel: "Hủy",
    saveSuccess: "Đã gửi dữ liệu sang Admin",
    saveError: "Lưu thất bại, thử lại",
    departmentLabel: "Bộ phận (vd: Ép Phun 1, Bảo Trì...)",
    departmentPlaceholder: "Nhập bộ phận của bạn..."
  },
  en: {
    title: "AI Consultant",
    subtitle: "Quick Analysis",
    version: "v2.0 PRO",
    location: "Duy Tan Binh Duong • Technical Intelligence",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    optimizeCycle: "Cycle Optimization",
    optimizeCycleDesc: "11 categories deep analysis.",
    captureParams: "Parameter Capture",
    captureParamsDesc: "AI extracts data from machine screen photos.",
    aiExpert: "AI Expert",
    aiExpertDesc: "24/7 Duy Tan technical solutions support.",
    processing: "AI Processing...",
    ready: "Analysis Ready",
    newSession: "New Session",
    optimizationReport: "Quick Analysis",
    aiAssistant: "AI Technical Assistant",
    thinking: "AI is thinking...",
    chatPlaceholder: "Ask about cooling, materials...",
    footer: "© 2024 AI Injection Molding Optimization v2.0 - Duy Tan Binh Duong Technical",
    error: "An error occurred during data analysis. Please check your connection or AI.",
    noResponse: "No response from AI.",
    connectionError: "Connection error.",
    expertReplyError: "Sorry, I cannot answer.",
    langVi: "Vietnamese",
    langEn: "English",
    langTh: "Thai",
    langViEn: "Viet - Eng",
    inputParams: "Input Parameters",
    excelLabel: "Excel/CSV Data Row (Tab or Comma)",
    excelPlaceholder: "Column order: Brand, Model, Tonnage, Product, Weight, Cavities, Cycle Time, Injection, Holding, Cooling, Charging, Mold Close, Mold Open, Ejection, Melt Temp, Mold Temp, Injection Pressure, Injection Speed, Close Speed, Open Speed, Ejection Speed, Charging Speed, Back Pressure, Screw Speed, Cushion, Actual Clamping, Defect Rate, Notes",
    screenshotLabel: "Machine Screen Screenshot",
    uploadPhoto: "Upload Screenshot",
    takePhoto: "Take Photo",
    fromGallery: "From Gallery",
    techNotes: "Technical Notes",
    techNotesPlaceholder: "e.g., Focus on reducing cooling time from 15s to 10s, check mold temperature...",
    analyzeBtn: "QUICK ANALYSIS",
    resetBtn: "Reset",
    alertInput: "Please paste data or upload a parameter image.",
    chartCurrent: "Current",
    chartOptimized: "Optimized",
    chartCycleTime: "Total Cycle",
    chartCooling: "Cooling",
    chartInjection: "Injection",
    chartHolding: "Holding",
    chartCharging: "Charging",
    chartMoldClose: "Mold Close",
    chartMoldOpen: "Mold Open",
    chartEjection: "Ejection",
    chartOthers: "Others",
    instCloseSpeed: "Mold Close {name}: Increase speed from {orig}% to {curr}%",
    instClosePos: "Mold Close {name}: Adjust position from {orig}mm to {curr}mm",
    instOpenSpeed: "Mold Open {name}: Increase speed from {orig}% to {curr}%",
    instOpenPos: "Mold Open {name}: Adjust position from {orig}mm to {curr}mm",
    instInjSpeed: "Injection {name}: Adjust speed from {orig}% to {curr}%",
    instInjPos: "Injection {name}: Adjust position from {orig}mm to {curr}mm",
    instHoldPress: "Holding {name}: Adjust pressure from {orig} bar to {curr} bar",
    instHoldTime: "Holding {name}: Adjust time from {orig}s to {curr}s",
    instChargeSpeed: "Charging {name}: Adjust speed from {orig}% to {curr}%",
    instChargePos: "Charging {name}: Adjust position from {orig}mm to {curr}mm",
    instCooling: "Cooling Time: Reduce from {orig}s to {curr}s",
    simTitle: "Quick Analysis",
    moldName: "Mold Name",
    simDesc: "Compare standard parameters with AI-proposed adjustments",
    simCurrent: "Current Cycle",
    simSimulated: "Simulated Cycle",
    tableStandard: "Table 1: Standard Parameters (Current)",
    tableProposed: "Table 2: AI Proposed & Simulated",
    stage: "STAGE",
    speed: "Speed (%)",
    position: "Position (mm)",
    pressure: "Pressure (bar)",
    time: "Time (s)",
    moldClose: "MOLD CLOSE (F3)",
    moldOpen: "MOLD OPEN",
    injection: "INJECTION",
    holding: "HOLDING",
    charging: "CHARGING",
    cooling: "COOLING",
    coolStdTime: "Standard Cooling Time",
    coolAdjTime: "Adjust Cooling Time",
    ejection: "EJECTION",
    adjustment: "ADJUSTMENT",
    expected: "Expected",
    standard: "Standard",
    confirmed: "ADJUSTMENT CONFIRMED",
    confirmBtn: "CONFIRM & EXPORT INSTRUCTIONS",
    instTitle: "DETAILED ADJUSTMENT INSTRUCTIONS",
    instSubtitle: "Follow these steps exactly on the machine screen",
    printBtn: "Print Instructions",
    chartBrandTitle: "Average Cycle by Brand (s)",
    chartCompositionTitle: "Cycle Composition",
    chartTitle: "CYCLE COMPARISON CHART (SECONDS)",
    diffChart: "Detailed Difference Chart",
    tableDetail: "Detailed Cycle Comparison Table",
    item: "Item",
    saving: "Saving",
    coreIn: "Core In",
    coreOut: "Core Out",
    robot: "Total SP (Robot)",
    waitRobot: "Wait Robot",
    adminDashboard: "Admin Dashboard",
    usageHistory: "Usage History",
    totalAnalyses: "Total Analyses",
    activeUsers: "Active Users",
    todayAnalyses: "Today's Analyses",
    weekAnalyses: "This Week's Analyses",
    errorAnalyses: "Error Records",
    topDepartment: "Top Department",
    historyTime: "Time",
    user: "User",
    email: "Email",
    department: "Department",
    language: "Language",
    status: "Status",
    currentCycle: "Current Cycle",
    targetCycle: "Target Cycle",
    estimatedReduction: "Est. Reduction",
    viewDetail: "View Detail",
    filterByDate: "Filter by Date",
    filterByUser: "Filter by User",
    filterByDept: "Filter by Dept",
    filterByStatus: "Filter by Status",
    filterByLang: "Filter by Lang",
    searchPlaceholder: "Search by email or name...",
    exportExcel: "Export Excel",
    exportCsv: "Export CSV",
    printReport: "Print Report",
    deleteRecord: "Delete Record",
    confirmDelete: "Are you sure you want to delete this record?",
    analysisDetail: "Analysis Detail",
    inputData: "Input Data",
    aiRecommendations: "AI Recommendations",
    processingTime: "Processing Time",
    loginWithGoogle: "Login with Google",
    logout: "Logout",
    notAuthorized: "You are not authorized to access this page.",
    backToApp: "Back to App",
    statsByDay: "Usage by Day",
    topUsers: "Top Users",
    topDepts: "Top Departments",
    statusRatio: "Status Ratio",
    avgReduction: "Avg Cycle Reduction",
    all: "All",
    completed: "Completed",
    errorStatus: "Error",
    processingStatus: "Processing",
    actions: "Actions",
    noRecords: "No records found",
    usersList: "User List",
    viewHistory: "View History",
    lastActive: "Last Active",
    totalAnalysesUser: "Total Analyses",
    role: "Role",
    recordsTab: "Records",
    usersTab: "Users",
    confirmSaveTitle: "Analysis Result",
    confirmSaveContent: "Do you want fast consulting analysis results?",
    confirmOk: "Confirm OK",
    cancel: "Cancel",
    saveSuccess: "Data sent to Admin",
    saveError: "Save failed, try again",
    departmentLabel: "Department (e.g., Injection 1, Maintenance...)",
    departmentPlaceholder: "Enter your department..."
  },
  th: {
    title: "ที่ปรึกษา AI",
    subtitle: "การวิเคราะห์ด่วน",
    version: "v2.0 PRO",
    location: "Duy Tan Binh Duong • Technical Intelligence",
    darkMode: "โหมดมืด",
    lightMode: "โหมดสว่าง",
    optimizeCycle: "การเพิ่มประสิทธิภาพรอบเวลา",
    optimizeCycleDesc: "การวิเคราะห์เชิงลึก 11 หมวดหมู่",
    captureParams: "จับภาพพารามิเตอร์",
    captureParamsDesc: "AI ดึงข้อมูลจากภาพถ่ายหน้าจอเครื่อง",
    aiExpert: "ผู้เชี่ยวชาญ AI",
    aiExpertDesc: "สนับสนุนโซลูชันทางเทคนิค Duy Tan 24/7",
    processing: "AI กำลังประมวลผล...",
    ready: "พร้อมสำหรับการวิเคราะห์",
    newSession: "เซสชันใหม่",
    optimizationReport: "การวิเคราะห์ด่วน",
    aiAssistant: "ผู้ช่วยด้านเทคนิค AI",
    thinking: "AI กำลังคิด...",
    chatPlaceholder: "ถามเกี่ยวกับการทำความเย็น วัสดุ...",
    footer: "© 2024 AI การเพิ่มประสิทธิภาพการฉีดขึ้นรูป v2.0 - Duy Tan Binh Duong Technical",
    error: "เกิดข้อผิดพลาดระหว่างการวิเคราะห์ข้อมูล โปรดตรวจสอบการเชื่อมต่อหรือ AI ของคุณ",
    noResponse: "ไม่มีการตอบสนองจาก AI",
    connectionError: "ข้อผิดพลาดในการเชื่อมต่อ",
    expertReplyError: "ขออภัย ฉันไม่สามารถตอบได้",
    langVi: "เวียดนาม",
    langEn: "อังกฤษ",
    langTh: "ไทย",
    langViEn: "เวียดนาม - อังกฤษ",
    inputParams: "พารามิเตอร์อินพุต",
    excelLabel: "แถวข้อมูล Excel/CSV (แท็บหรือจุลภาค)",
    excelPlaceholder: "ลำดับคอลัมน์: ยี่ห้อ, รุ่น, น้ำหนักบรรทุก, ผลิตภัณฑ์, น้ำหนัก, โพรง, รอบเวลา, การฉีด, การถือครอง, การทำความเย็น, การชาร์จ, การปิดแม่พิมพ์, การเปิดแม่พิมพ์, การดีดออก, อุณหภูมิหลอมละลาย, อุณหภูมิแม่พิมพ์, แรงดันการฉีด, ความเร็วการฉีด, ความเร็วในการปิด, ความเร็วในการเปิด, ความเร็วในการดีดออก, ความเร็วในการชาร์จ, แรงดันย้อนกลับ, ความเร็วสกรู, เบาะรองนั่ง, การหนีบจริง, อัตราข้อบกพร่อง, หมายเหตุ",
    screenshotLabel: "ภาพหน้าจอเครื่อง",
    uploadPhoto: "อัปโหลดภาพหน้าจอ",
    takePhoto: "ถ่ายภาพ",
    fromGallery: "จากคลังภาพ",
    techNotes: "บันทึกทางเทคนิค",
    techNotesPlaceholder: "เช่น เน้นลดเวลาการทำความเย็นจาก 15 วินาทีเหลือ 10 วินาที ตรวจสอบอุณหภูมิแม่พิมพ์...",
    analyzeBtn: "การวิเคราะห์ด่วน",
    resetBtn: "รีเซ็ต",
    alertInput: "โปรดวางข้อมูลหรืออัปโหลดภาพพารามิเตอร์",
    chartCurrent: "ปัจจุบัน",
    chartOptimized: "เพิ่มประสิทธิภาพ",
    chartCycleTime: "รอบรวม",
    chartCooling: "ระบายความร้อน",
    chartInjection: "การฉีด",
    chartHolding: "การถือครอง",
    chartCharging: "การชาร์จ",
    chartMoldClose: "ปิดแม่พิมพ์",
    chartMoldOpen: "เปิดแม่พิมพ์",
    chartEjection: "การดีดออก",
    chartOthers: "อื่นๆ",
    instCloseSpeed: "ปิดแม่พิมพ์ {name}: เพิ่มความเร็วจาก {orig}% เป็น {curr}%",
    instClosePos: "ปิดแม่พิมพ์ {name}: ปรับตำแหน่งจาก {orig} มม. เป็น {curr} มม.",
    instOpenSpeed: "เปิดแม่พิมพ์ {name}: เพิ่มความเร็วจาก {orig}% เป็น {curr}%",
    instOpenPos: "เปิดแม่พิมพ์ {name}: ปรับตำแหน่งจาก {orig} มม. เป็น {curr} มม.",
    instInjSpeed: "การฉีด {name}: ปรับความเร็วจาก {orig}% เป็น {curr}%",
    instInjPos: "การฉีด {name}: ปรับตำแหน่งจาก {orig} มม. เป็น {curr} มม.",
    instHoldPress: "การถือครอง {name}: ปรับแรงดันจาก {orig} บาร์ เป็น {curr} บาร์",
    instHoldTime: "การถือครอง {name}: ปรับเวลาจาก {orig} วินาที เป็น {curr} วินาที",
    instChargeSpeed: "การชาร์จ {name}: ปรับความเร็วจาก {orig}% เป็น {curr}%",
    instChargePos: "การชาร์จ {name}: ปรับตำแหน่งจาก {orig} มม. เป็น {curr} มม.",
    instCooling: "เวลาทำความเย็น: ลดจาก {orig} วินาทีเหลือ {curr} วินาที",
    simTitle: "การวิเคราะห์ด่วน",
    moldName: "ชื่อแม่พิมพ์",
    simDesc: "เปรียบเทียบพารามิเตอร์มาตรฐานกับการปรับเปลี่ยนที่ AI เสนอ",
    simCurrent: "รอบปัจจุบัน",
    simSimulated: "รอบจำลอง",
    tableStandard: "ตารางที่ 1: พารามิเตอร์มาตรฐาน (ปัจจุบัน)",
    tableProposed: "ตารางที่ 2: AI เสนอและจำลอง",
    stage: "ขั้นตอน",
    speed: "ความเร็ว (%)",
    position: "ตำแหน่ง (มม.)",
    pressure: "แรงดัน (บาร์)",
    time: "เวลา (วินาที)",
    moldClose: "ปิดแม่พิมพ์ (F3)",
    moldOpen: "เปิดแม่พิมพ์",
    injection: "การฉีด",
    holding: "การถือครอง",
    charging: "การชาร์จ",
    cooling: "ระบายความร้อน",
    coolStdTime: "เวลาทำความเย็นมาตรฐาน",
    coolAdjTime: "ปรับเวลาทำความเย็น",
    ejection: "การดีดออก",
    adjustment: "การปรับเปลี่ยน",
    expected: "คาดการณ์",
    standard: "มาตรฐาน",
    confirmed: "ยืนยันการปรับเปลี่ยนแล้ว",
    confirmBtn: "ยืนยันและส่งออกคำแนะนำ",
    instTitle: "คำแนะนำการปรับเปลี่ยนโดยละเอียด",
    instSubtitle: "ทำตามขั้นตอนเหล่านี้ให้ถูกต้องบนหน้าจอเครื่อง",
    printBtn: "พิมพ์คำแนะนำ",
    chartBrandTitle: "รอบเฉลี่ยตามยี่ห้อ (วินาที)",
    chartCompositionTitle: "องค์ประกอบของรอบ",
    chartTitle: "แผนภูมิเปรียบเทียบรอบ (วินาที)",
    diffChart: "แผนภูมิความแตกต่างโดยละเอียด",
    tableDetail: "ตารางเปรียบเทียบรอบโดยละเอียด",
    item: "รายการ",
    saving: "การประหยัด",
    coreIn: "แกนใน",
    coreOut: "แกนนอก",
    robot: "รวม SP (หุ่นยนต์)",
    waitRobot: "รอหุ่นยนต์",
    adminDashboard: "แผงควบคุมผู้ดูแลระบบ",
    usageHistory: "ประวัติการใช้งาน",
    totalAnalyses: "การวิเคราะห์ทั้งหมด",
    activeUsers: "ผู้ใช้งานที่ใช้งานอยู่",
    todayAnalyses: "การวิเคราะห์วันนี้",
    weekAnalyses: "การวิเคราะห์สัปดาห์นี้",
    errorAnalyses: "บันทึกข้อผิดพลาด",
    topDepartment: "แผนกยอดนิยม",
    historyTime: "เวลา",
    user: "ผู้ใช้",
    email: "อีเมล",
    department: "แผนก",
    language: "ภาษา",
    status: "สถานะ",
    currentCycle: "รอบปัจจุบัน",
    targetCycle: "รอบเป้าหมาย",
    estimatedReduction: "การลดที่คาดการณ์",
    viewDetail: "ดูรายละเอียด",
    filterByDate: "กรองตามวันที่",
    filterByUser: "กรองตามผู้ใช้",
    filterByDept: "กรองตามแผนก",
    filterByStatus: "กรองตามสถานะ",
    filterByLang: "กรองตามภาษา",
    searchPlaceholder: "ค้นหาตามอีเมลหรือชื่อ...",
    exportExcel: "ส่งออก Excel",
    exportCsv: "ส่งออก CSV",
    printReport: "พิมพ์รายงาน",
    deleteRecord: "ลบบันทึก",
    confirmDelete: "คุณแน่ใจหรือไม่ว่าต้องการลบบันทึกนี้?",
    analysisDetail: "รายละเอียดการวิเคราะห์",
    inputData: "ข้อมูลอินพุต",
    aiRecommendations: "คำแนะนำ AI",
    processingTime: "เวลาประมวลผล",
    loginWithGoogle: "เข้าสู่ระบบด้วย Google",
    logout: "ออกจากระบบ",
    notAuthorized: "คุณไม่มีสิทธิ์เข้าถึงหน้านี้",
    backToApp: "กลับไปที่แอป",
    statsByDay: "การใช้งานตามวัน",
    topUsers: "ผู้ใช้ยอดนิยม",
    topDepts: "แผนกยอดนิยม",
    statusRatio: "อัตราส่วนสถานะ",
    avgReduction: "การลดรอบเฉลี่ย",
    all: "ทั้งหมด",
    completed: "เสร็จสมบูรณ์",
    errorStatus: "ข้อผิดพลาด",
    processingStatus: "กำลังประมวลผล",
    actions: "การดำเนินการ",
    noRecords: "ไม่พบข้อมูล",
    usersList: "รายชื่อผู้ใช้",
    viewHistory: "ดูประวัติ",
    lastActive: "ใช้งานล่าสุด",
    totalAnalysesUser: "การวิเคราะห์ทั้งหมด",
    role: "บทบาท",
    recordsTab: "บันทึก",
    usersTab: "ผู้ใช้",
    confirmSaveTitle: "ยืนยันการบันทึกผลลัพธ์",
    confirmSaveContent: "คุณต้องการส่งผลการวิเคราะห์นี้ไปยังระบบผู้ดูแลระบบหรือไม่?",
    confirmOk: "ยืนยันตกลง",
    cancel: "ยกเลิก",
    saveSuccess: "ส่งข้อมูลไปยังผู้ดูแลระบบแล้ว",
    saveError: "บันทึกไม่สำเร็จ โปรดลองอีกครั้ง",
    departmentLabel: "แผนก (เช่น การฉีด 1, การบำรุงรักษา...)",
    departmentPlaceholder: "ป้อนแผนกของคุณ..."
  },
  'vi-en': {
    title: "AI Tư Vấn / AI Consultant",
    subtitle: "Phân Tích Nhanh / Quick Analysis",
    version: "v2.0 PRO",
    location: "Duy Tân Bình Dương • Technical Intelligence",
    darkMode: "Chế độ Tối / Dark Mode",
    lightMode: "Chế độ Sáng / Light Mode",
    optimizeCycle: "Tối ưu Chu kỳ / Cycle Optimization",
    optimizeCycleDesc: "Phân tích 11 hạng mục / 11 categories analysis.",
    captureParams: "Chụp ảnh / Capture",
    captureParamsDesc: "AI trích xuất dữ liệu / AI extracts data.",
    aiExpert: "Chuyên gia AI / AI Expert",
    aiExpertDesc: "Hỗ trợ 24/7 / 24/7 Support.",
    processing: "AI Đang Xử Lý... / AI Processing...",
    ready: "Phân Tích Sẵn Sàng / Analysis Ready",
    newSession: "Phiên Mới / New Session",
    optimizationReport: "Phân Tích Nhanh / Quick Analysis",
    aiAssistant: "Trợ Lý Kỹ Thuật AI / AI Technical Assistant",
    thinking: "AI đang suy nghĩ... / AI is thinking...",
    chatPlaceholder: "Hỏi về làm nguội... / Ask about cooling...",
    footer: "© 2024 AI Tối Ưu Hóa Ép Phun v2.0 - Duy Tan Binh Duong Technical",
    error: "Lỗi phân tích / Analysis error.",
    noResponse: "Không có phản hồi / No response.",
    connectionError: "Lỗi kết nối / Connection error.",
    expertReplyError: "Không thể trả lời / Cannot answer.",
    langVi: "Tiếng Việt",
    langEn: "English",
    langTh: "ไทย",
    langViEn: "Việt - Anh",
    inputParams: "Thông Số Đầu Vào / Input Parameters",
    excelLabel: "Dữ Liệu Excel/CSV / Excel/CSV Data",
    excelPlaceholder: "Thứ tự cột / Column order: Brand, Model, Tonnage, Product, Weight, Cavities, Cycle Time...",
    screenshotLabel: "Chụp Ảnh Màn Hình / Screenshot",
    uploadPhoto: "Tải Ảnh / Upload Photo",
    takePhoto: "Chụp ảnh / Take Photo",
    fromGallery: "Chọn từ thư viện / Gallery",
    techNotes: "Ghi Chú / Technical Notes",
    techNotesPlaceholder: "vd: Giảm làm nguội / e.g., Reduce cooling...",
    analyzeBtn: "PHÂN TÍCH NHANH / QUICK ANALYSIS",
    resetBtn: "Đặt Lại / Reset",
    alertInput: "Vui lòng nhập dữ liệu / Please input data.",
    chartCurrent: "Hiện tại / Current",
    chartOptimized: "Tối ưu / Optimized",
    chartCycleTime: "Tổng chu kỳ / Total Cycle",
    chartCooling: "Làm mát / Cooling",
    chartInjection: "Phun nhựa / Injection",
    chartHolding: "Giữ áp / Holding",
    chartCharging: "Nạp nhựa / Charging",
    chartMoldClose: "Đóng khuôn / Mold Close",
    chartMoldOpen: "Mở khuôn / Mold Open",
    chartEjection: "Lừa/Đẩy / Ejection",
    chartOthers: "Khác / Others",
    instCloseSpeed: "Đóng kềm {name}: Speed {orig}% -> {curr}%",
    instClosePos: "Đóng kềm {name}: Pos {orig}mm -> {curr}mm",
    instOpenSpeed: "Mở kềm {name}: Speed {orig}% -> {curr}%",
    instOpenPos: "Mở kềm {name}: Pos {orig}mm -> {curr}mm",
    instInjSpeed: "Bơm keo {name}: Speed {orig}% -> {curr}%",
    instInjPos: "Bơm keo {name}: Pos {orig}mm -> {curr}mm",
    instHoldPress: "Giữ áp {name}: Press {orig} -> {curr} bar",
    instHoldTime: "Giữ áp {name}: Time {orig}s -> {curr}s",
    instChargeSpeed: "Nạp nhựa {name}: Speed {orig}% -> {curr}%",
    instChargePos: "Nạp nhựa {name}: Pos {orig}mm -> {curr}mm",
    instCooling: "Làm mát / Cooling: {orig}s -> {curr}s",
    simTitle: "Phân Tích Nhanh / Quick Analysis",
    moldName: "Tên khuôn / Mold Name",
    simDesc: "Đối chiếu thông số / Compare parameters",
    simCurrent: "Hiện tại / Current",
    simSimulated: "Mô phỏng / Simulated",
    tableStandard: "Thông Số Chuẩn / Standard Params",
    tableProposed: "Đề Xuất AI / AI Proposed",
    stage: "GIAI ĐOẠN / STAGE",
    speed: "Tốc độ / Speed (%)",
    position: "Vị trí / Pos (mm)",
    pressure: "Áp lực / Press (bar)",
    time: "Thời gian / Time (s)",
    moldClose: "ĐÓNG KỀM / MOLD CLOSE",
    moldOpen: "MỞ KỀM / MOLD OPEN",
    injection: "BƠM KEO / INJECTION",
    holding: "GIỮ ÁP / HOLDING",
    charging: "NẠP NHỰA / CHARGING",
    cooling: "LÀM MÁT / COOLING",
    coolStdTime: "Làm mát chuẩn / Std Cooling",
    coolAdjTime: "Chỉnh làm mát / Adj Cooling",
    ejection: "LỪA / EJECTION",
    adjustment: "ĐIỀU CHỈNH / ADJUST",
    expected: "Dự kiến / Exp",
    standard: "Chuẩn / Std",
    confirmed: "ĐÃ XÁC NHẬN / CONFIRMED",
    confirmBtn: "XÁC NHẬN / CONFIRM",
    instTitle: "HƯỚNG DẪN / INSTRUCTIONS",
    instSubtitle: "Thực hiện trên máy / Follow on machine",
    printBtn: "In / Print",
    chartBrandTitle: "Chu Kỳ Theo Thương Hiệu / Cycle by Brand",
    chartCompositionTitle: "Cấu Thành Chu Kỳ / Cycle Composition",
    chartTitle: "SO SÁNH CHU KỲ / CYCLE COMPARISON",
    diffChart: "Biểu Đồ Chênh Lệch / Diff Chart",
    tableDetail: "Bảng So Sánh / Comparison Table",
    item: "Hạng mục / Item",
    saving: "Tiết kiệm / Saving",
    coreIn: "Trung tử vào / Core In",
    coreOut: "Trung tử ra / Core Out",
    robot: "Robot",
    waitRobot: "Chờ robot / Wait Robot",
    adminDashboard: "Bảng Admin / Admin Dashboard",
    usageHistory: "Lịch sử / Usage History",
    totalAnalyses: "Tổng phân tích / Total Analyses",
    activeUsers: "User hoạt động / Active Users",
    todayAnalyses: "Hôm nay / Today",
    weekAnalyses: "Tuần này / This Week",
    errorAnalyses: "Record lỗi / Error Records",
    topDepartment: "Bộ phận top / Top Dept",
    historyTime: "Thời gian / Time",
    user: "Người dùng / User",
    email: "Email",
    department: "Bộ phận / Dept",
    language: "Ngôn ngữ / Lang",
    status: "Trạng thái / Status",
    currentCycle: "Chu kỳ hiện tại / Current Cycle",
    targetCycle: "Chu kỳ mục tiêu / Target Cycle",
    estimatedReduction: "Mức giảm / Reduction",
    viewDetail: "Chi tiết / View Detail",
    filterByDate: "Lọc ngày / Filter Date",
    filterByUser: "Lọc user / Filter User",
    filterByDept: "Lọc bộ phận / Filter Dept",
    filterByStatus: "Lọc trạng thái / Filter Status",
    filterByLang: "Lọc ngôn ngữ / Filter Lang",
    searchPlaceholder: "Tìm kiếm / Search...",
    exportExcel: "Xuất Excel",
    exportCsv: "Xuất CSV",
    printReport: "In báo cáo / Print",
    deleteRecord: "Xóa / Delete",
    confirmDelete: "Xác nhận xóa? / Confirm delete?",
    analysisDetail: "Chi tiết / Detail",
    inputData: "Dữ liệu / Input Data",
    aiRecommendations: "Đề xuất AI / AI Recs",
    processingTime: "Xử lý / Processing Time",
    loginWithGoogle: "Đăng nhập Google / Login",
    logout: "Đăng xuất / Logout",
    notAuthorized: "Không có quyền / Not authorized",
    backToApp: "Quay lại / Back",
    statsByDay: "Theo ngày / By Day",
    topUsers: "Top Users",
    topDepts: "Top Depts",
    statusRatio: "Tỷ lệ / Ratio",
    avgReduction: "Giảm TB / Avg Reduction",
    all: "Tất cả / All",
    completed: "Xong / Done",
    errorStatus: "Lỗi / Error",
    processingStatus: "Đang xử lý / Processing",
    actions: "Thao tác / Actions",
    noRecords: "Không tìm thấy dữ liệu / No records found",
    usersList: "Danh sách người dùng / User List",
    viewHistory: "Xem lịch sử / View History",
    lastActive: "Hoạt động cuối / Last Active",
    totalAnalysesUser: "Tổng số lượt / Total Analyses",
    role: "Vai trò / Role",
    recordsTab: "Bản ghi / Records",
    usersTab: "Người dùng / Users",
    confirmSaveTitle: "Kết quả phân tích / Analysis Result",
    confirmSaveContent: "Bạn có muốn kết quả phân tích tư vấn nhanh? / Do you want fast consulting analysis results?",
    confirmOk: "Xác nhận OK / Confirm OK",
    cancel: "Hủy / Cancel",
    saveSuccess: "Đã gửi / Data sent",
    saveError: "Lỗi lưu / Save error",
    departmentLabel: "Bộ phận / Department (vd: Ép Phun 1...)",
    departmentPlaceholder: "Nhập bộ phận / Enter department..."
  }
};
